### ISSUE TITLE
max-height stripped out

### ISSUE THREAD

**Issue by patrickmj** [omeka/plugin-CSSEditor#2]
Per the forums, https://forum.omeka.org/t/how-to-resize-collection-thumbnail/4533/3 `max-height` style is being stripped out. `height` remains just fine. 

Is this a CSSTidy setting?

**Comment by zerocrates** [comment]
HTMLPurifier just doesn't support it.

**Comment by zerocrates** [comment]
It looks like there may be an update that does though? Will have to look into it. That would be a core change though.

**Comment by kalbers** [comment]
I think it's the same for max-width too.
