### ISSUE TITLE
Filtering of selectors and properties

### ISSUE THREAD

**Issue by ebellempire** [omeka/plugin-CSSEditor#7]
Helping out with an omeka.net project that uses the CSS Editor plugin and I'm noticing that the validator is filtering out many useful features of modern CSS (e.g. `object-fit`, `display:flex`, etc) and that even some basic selectors like `audio` are filtered out. Are there any plans to change this?

**Comment by zerocrates** [comment]
HTMLPurifier, which is what's used here, doesn't know about and therefore allow much of modern CSS. We can pretty easily add support for element selectors that are missing, actual properties are trickier.

`audio` looks like an oversight that could be corrected.

We've done some initial thinking/looking about alternatives to HTMLPurifier but I have nothing concrete for you on a likely change there.

**Comment by ebellempire** [comment]
Ok, thanks.
